id: 93ae048458d74106b3ab18afb106e7b4
initial_creation_type: ocr
source_metadata:
  volumes:
    d88236c3d23445338d70b418d6423d71:
      base_file: v015.txt
      image_group_id: I1PD95860
      title: ''
      total_pages: 1453
      volume_number: 15
